### ISSUE TITLE
Not able to download checkpoint from Drive

### ISSUE THREAD

**Issue by harpavatkeerti** [praveenjune17/BERT_text_summarisation#1]
Hi, 
I wanted to run the colab demo as this seems an interesting work. But it is giving the following error:
```ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /root/ckpt_dir/drive/My Drive/Text_summarization/BERT_text_summarisation/Summarization_inference_ckps/ckpt-75: Not found: /root/ckpt_dir/drive/My Drive/Text_summarization/BERT_text_summarisation/Summarization_inference_ckps; No such file or directory```
Also, can I get a link to the pretrained model (if the problem in colab is not fixed)?
Thanks in advance

**Comment by praveenjune17** [comment]
Please find the link to the model.. https://drive.google.com/uc?export=download&confirm=J6_X&id=1-9Xjo41IDfgaoGXjdEyBmhucK2CHpkaZ . If you want to try advanced summarization models then please have a look at hugging face summarization notebooks..

**Comment by harpavatkeerti** [comment]
Thank you very much.

**Comment by praveenjune17** [comment]
you could use this [repo](https://github.com/praveenjune17/transformers-with-2stagedecoders/tree/master/scripts) for training a summarization or translation model using the same architecture discussed in the paper.. Have added policy gradients feature and BERT score (coded in tensorflow) .
